name = "LuxCore"
uuid = "bb33d45b-7691-41d6-9220-0943567d0623"
authors = ["Avik Pal <avikpal@mit.edu> and contributors"]
version = "0.1.23"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DispatchDoctor = "8d63f2c5-f18a-4cf2-ba9d-b3f60fc568c8"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"

[weakdeps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
MLDataDevices = "7e8f7934-dd98-4c1a-8fe8-92b47a384d40"
EnzymeCore = "f151be2c-9106-41f4-ab19-57ee4f262869"

[extensions]
LuxCoreChainRulesCoreExt = "ChainRulesCore"
LuxCoreMLDataDevicesExt = "MLDataDevices"
LuxCoreEnzymeCoreExt = "EnzymeCore"

[compat]
ChainRulesCore = "1.24"
Compat = "4.15.0"
DispatchDoctor = "0.4.10"
EnzymeCore = "0.7.7"
Functors = "0.4.12"
MLDataDevices = "1"
Random = "1.10"
Setfield = "1"
julia = "1.10"
